CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++11

DEMO_BIN = demo
TEST_BIN = test

all: help

help:
	@echo "Available commands:"
	@echo "  make module    - Build the ArrayQueue.o module"
	@echo "  make build_demo - Build the demo executable"
	@echo "  make run_demo   - Run the demo executable"
	@echo "  make build_test - Build the test executable"
	@echo "  make run_test   - Run the test executable"
	@echo "  make clean      - Remove compiled objects and executables"
	@echo "  make rebuild    - Clean everything and rebuild demo and test"

module: ArrayQueue.o

ArrayQueue.o: ArrayQueue.cpp ArrayQueue.h
	$(CXX) $(CXXFLAGS) -c ArrayQueue.cpp -o ArrayQueue.o

build_demo: ArrayQueue.o demo.cpp
	$(CXX) $(CXXFLAGS) demo.cpp ArrayQueue.o -o $(DEMO_BIN)

run_demo: build_demo
	./$(DEMO_BIN)

build_test: ArrayQueue.o test.cpp
	$(CXX) $(CXXFLAGS) test.cpp ArrayQueue.o -o $(TEST_BIN)

run_test: build_test
	./$(TEST_BIN)

clean:
	rm -f *.o $(DEMO_BIN) $(TEST_BIN) log.txt

rebuild: clean build_demo build_test
